//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Adresse
{
	public virtual string Vejnavn
	{
		get;
		set;
	}

	public virtual string Husnummer
	{
		get;
		set;
	}

	public virtual int Postummer
	{
		get;
		set;
	}

	public virtual string Bynavn
	{
		get;
		set;
	}

	public virtual string Type
	{
		get;
		set;
	}

}

