//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Telefon
{
	public virtual string TelefonNummer
	{
		get;
		set;
	}

	public virtual string Type
	{
		get;
		set;
	}

}

