//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Person
{
    public string PersonNummer { get; set; }

	public virtual string Efternavn
	{
		get;
		set;
	}

	public virtual string Fornavn
	{
		get;
		set;
	}

	public virtual string Mellemnavn
	{
		get;
		set;
	}

	public virtual string Type
	{
		get;
		set;
	}

	public virtual Adresse Adresse
	{
		get;
		set;
	}

	public virtual List<Adresse> Adresser
	{
		get;
		set;
	}

	public virtual List<Telefon> Telefon
	{
		get;
		set;
	}

}

