//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GLDReverse
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appartmentcharacteristic
    {
        public int AppartmentId { get; set; }
        public int No { get; set; }
        public float Size { get; set; }
        public int Floor { get; set; }
        public Nullable<int> CharacteristicContainer_CharacteristicContainerId { get; set; }
    
        public virtual CharacteristicContainer CharacteristicContainer { get; set; }
    }
}
