//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GLDReverse
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reading
    {
        public int ReadingId { get; set; }
        public int sensorId { get; set; }
        public int appartmentId { get; set; }
        public float value { get; set; }
        public System.DateTime timestamp { get; set; }
        public Nullable<int> ReadingContainer_ReadingContainerId { get; set; }
    
        public virtual ReadingContainer ReadingContainer { get; set; }
    }
}
