//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GLDReverse
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sensorcharacteristic
    {
        public int sensorId { get; set; }
        public string calibrationCoeff { get; set; }
        public string description { get; set; }
        public System.DateTime calibrationDate { get; set; }
        public string externalRef { get; set; }
        public string unit { get; set; }
        public string calibrationEquation { get; set; }
        public Nullable<int> CharacteristicContainer_CharacteristicContainerId { get; set; }
    
        public virtual CharacteristicContainer CharacteristicContainer { get; set; }
    }
}
